### PR TITLE
fix: camerastate saver should save dp as primitive

### LINKED ISSUE #337: Crash Parcel: unknown type for value 0.0.dp
### What happened?

After #277 I got crash.
```
  Fatal Exception: java.lang.IllegalArgumentException: Parcel: unknown type for value 0.0.dp
       at android.os.Parcel.getValueType(Parcel.java:2455)
       at android.os.Parcel.writeValue(Parcel.java:2354)
       at android.os.Parcel.writeMapInternal(Parcel.java:1266)
       at android.os.Parcel.writeMap(Parcel.java:1248)
       at android.os.Parcel.writeValue(Parcel.java:2476)
       at android.os.Parcel.writeValue(Parcel.java:2362)
       at android.os.Parcel.writeList(Parcel.java:1415)
       at android.os.Parcel.writeValue(Parcel.java:2506)
       at android.os.Parcel.writeValue(Parcel.java:2362)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
       at android.os.Bundle.writeToParcel(Bundle.java:1389)
       at android.os.Parcel.writeBundle(Parcel.java:1367)
       at android.os.Parcel.writeValue(Parcel.java:2479)
       at android.os.Parcel.writeValue(Parcel.java:2369)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
       at android.os.Bundle.writeToParcel(Bundle.java:1389)
       at android.os.Parcel.writeBundle(Parcel.java:1367)
       at android.os.Parcel.writeValue(Parcel.java:2479)
       at android.os.Parcel.writeValue(Parcel.java:2369)
       at android.os.BaseBundle.dumpStats(BaseBundle.java:1924)
       at android.os.BaseBundle.dumpStats(BaseBundle.java:1961)
       at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
       at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:224)
       at android.os.Looper.loop(Looper.java:318)
       at android.app.ActivityThread.main(ActivityThread.java:8763)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

Reproduction steps:
- run demo
- lock screen
- wait a few seconds
- unlock screen

### Affected Platforms

Android

### Platform Version

Android 14

### Library Version

Commit c3986a7

### Sample Code

None

### PR DESCRIPTION
**Pull request by sargunv**
untested, but should fix #337

### CODE REVIEW

**Comment by sargunv** [comment]
* **#338** <a href="https://app.graphite.dev/github/pr/sargunv/maplibre-compose/338?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/sargunv/maplibre-compose/338?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraStateSaver.kt [hunk 1]
```diff
@@ -5,44 +5,42 @@ import androidx.compose.foundation.layout.calculateEndPadding
...
+        position.padding.calculateStartPadding(LayoutDirection.Ltr).value.toDouble(),
+      Keys.PADDING_TOP to position.padding.calculateTopPadding().value.toDouble(),
+      Keys.PADDING_RIGHT to
+        position.padding.calculateEndPadding(LayoutDirection.Ltr).value.toDouble(),
+      Keys.PADDING_BOTTOM to position.padding.calculateBottomPadding().value.toDouble(),
     )
   }
 
-  override fun restore(value: Map<String, Any>): CameraState? {
+  override fun restore(value: Map<String, Double>): CameraState? {
```
Comment (michalgwo) [inline lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraStateSaver.kt:31]:
```suggestion
  override fun restore(value: Map<String, Double>): CameraState {
```

File: lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraStateSaver.kt [hunk 2]
```diff
@@ -5,44 +5,42 @@ import androidx.compose.foundation.layout.calculateEndPadding
...
-import androidx.compose.ui.unit.Dp
 import androidx.compose.ui.unit.LayoutDirection
+import androidx.compose.ui.unit.dp
 import dev.sargunv.maplibrecompose.core.CameraPosition
 import io.github.dellisd.spatialk.geojson.Position
 
-internal object CameraStateSaver : Saver<CameraState, Map<String, Any>> {
-  override fun SaverScope.save(value: CameraState): Map<String, Any>? {
+internal object CameraStateSaver : Saver<CameraState, Map<String, Double>> {
+  override fun SaverScope.save(value: CameraState): Map<String, Double>? {
```
Comment (michalgwo) [inline lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraStateSaver.kt:14]:
```suggestion
  override fun SaverScope.save(value: CameraState): Map<String, Double> {
```

**Review by michalgwo — APPROVED** [review]
It fixes the crash, thanks!

Maybe it's not part of this PR, but it's related. Does this line have any purpose, or is it just a mistake?

https://github.com/sargunv/maplibre-compose/blob/e85f2cf9becc858489c928459166916d224cfcf9/lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt#L30

**Comment by sargunv** [comment]
> Does this line have any purpose, or is it just a mistake?

just a mistake! removed it
